### ISSUE TITLE
adding Properties to Indirect and Direct Object, and possibly Aim (are adverbs a thing in written rules)

### ISSUE THREAD

**Issue by enfascination** [InstitutionalGrammar/IG-XML-Schema#1]

**Comment by chrfrantz** [comment]
Properties had already been added, including hierarchy (i.e., properties of properties). Let me know in case you see any glitches in specification. Properties of aims are execution constraints (they "qualify" the aim), so aims don't require additional properties. However, annotations are still to be added to various components (see ToDo).
